apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}

spec:
  replicas: 2
  revisionHistoryLimit: 2

  selector:
    matchLabels:
      app: {{ .Values.name }}

  template:
    metadata:
      name: proxy
      labels:
        app: {{ .Values.name }}
    spec:
      securityContext:
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: {{ .Values.name }}
              topologyKey: kubernetes.io/hostname
            weight: 100

      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Chart.Version }}"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL

          ports:
            - containerPort: 8000
              name: http

          volumeMounts:
            - mountPath: /tmp/nginx
              name: tmp-volume
            - mountPath: /var/cache/nginx
              name: cache-volume

          resources:
            requests:
              cpu: 100m
              memory: 30Mi
            limits:
              cpu: 100m
              memory: 30Mi

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 2
      
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: cache-volume
          emptyDir: {}

      serviceAccount: {{ .Values.name }}
      serviceAccountName: {{ .Values.name }}
